# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: JazzBloom
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics: null
  locale: en-US
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: local
    cdnCaching: false
    typography:
      header: Segoe UI
      body: Segoe UI
      code: Consolas
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#fff23688"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#b3aa0288"
plugins:
  - source: "@quartz-community/note-properties"
    enabled: true
    options:
      hidePropertiesView: true
    order: 5
  - source: "@quartz-community/obsidian-flavored-markdown"
    enabled: true
    order: 30
  - source: "@quartz-community/github-flavored-markdown"
    enabled: true
    order: 40
  - source: "@quartz-community/table-of-contents"
    enabled: true
    order: 50
    layout:
      position: right
      priority: 30
  - source: "@quartz-community/crawl-links"
    enabled: true
    options:
      markdownLinkResolution: shortest
    order: 60
  - source: "@quartz-community/description"
    enabled: true
    order: 70
  - source: "@quartz-community/remove-draft"
    enabled: true
  - source: "@quartz-community/alias-redirects"
    enabled: true
  - source: "@quartz-community/content-index"
    enabled: true
    options:
      enableSiteMap: false
      enableRSS: false
  - source: "@quartz-community/favicon"
    enabled: true
  - source: "@quartz-community/content-page"
    enabled: true
  - source: "@quartz-community/folder-page"
    enabled: true
    options:
      showFolderCount: false
  - source: "@quartz-community/explorer"
    enabled: true
    options:
      title: Contents
      folderClickBehavior: link
      folderDefaultState: collapsed
    layout:
      position: left
      priority: 50
  - source: "@quartz-community/search"
    enabled: true
    layout:
      position: left
      priority: 20
      group: toolbar
      groupOptions:
        grow: true
  - source: "@quartz-community/backlinks"
    enabled: true
    layout:
      position: right
      priority: 50
  - source: "@quartz-community/article-title"
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: "@quartz-community/page-title"
    enabled: true
    layout:
      position: left
      priority: 10
  - source: "@quartz-community/darkmode"
    enabled: true
    layout:
      position: left
      priority: 30
      group: toolbar
  - source: "@quartz-community/breadcrumbs"
    enabled: true
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: "@quartz-community/spacer"
    enabled: true
    layout:
      position: left
      priority: 25
      display: mobile-only
layout:
  groups:
    toolbar:
      priority: 35
      direction: row
      gap: 0.5rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder:
      positions:
        right: []
